# Generated by Django 3.0.2 on 2020-08-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='visible',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
